name: Build and Push Image to Artifact Registry
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    tags: v0.*

env:
  IMAGE_NAME: linux_tweet_app
  PROJECT_ID: linux-tweet-app

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t ${{env.IMAGE_NAME}}:latest .

  build-push-commit:
    name: Build and Push to Artifact Registry using commit SHA
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'branch' }}
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t ${{ env.IMAGE_NAME }}:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

    - name: Tag and Push Docker Image to Artifact Registry
      run: |-
        docker tag ${{ env.IMAGE_NAME }}:latest us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/artifacts/${{ env.IMAGE_NAME }}:latest
        docker tag ${{ env.IMAGE_NAME }}:latest us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/artifacts/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker push us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/artifacts/${{ env.IMAGE_NAME }}:latest
        docker push us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/artifacts/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  
  build-push-tag:
    name: Build and Push to Artifact Registry Using Tag
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get version from ref
      id: get_version
      uses: battila7/get-version-action@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t ${{ env.IMAGE_NAME }}:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

    - name: Tag and Push Docker Image to Artifact Registry
      env:
        IMAGE_TAG: ${{ steps.get_version.outputs.version }}
      run: |-
        docker tag ${{ env.IMAGE_NAME }}:latest us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/artifacts/${{ env.IMAGE_NAME }}:latest
        docker tag ${{ env.IMAGE_NAME }}:latest us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/artifacts/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker push us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/artifacts/${{ env.IMAGE_NAME }}:latest
        docker push us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/artifacts/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}