name: Build Docker Image
on:
  pull_request:
    branches: [ master ]

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: linux_tweet_app
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .
