name: Deploy to Cloud Run 
on: 
  push:
    branches:
      - master
      
env:
  IMAGE_NAME: tweet_app_el
  REGION: us-central1
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Copy Code
        uses: actions/checkout@v1
        
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v0.3.0
        with: 
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      
      - name: Build
        run: docker build -t $IMAGE_NAME:latest . 
      
      - name: Login to Registry
        run: |-
          gcloud auth configure-docker --quiet
          
      - name: Push to GCR
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/${{ secrets.PROJECT_ID }}/$IMAGE_NAME:latest
          docker push gcr.io/${{ secrets.PROJECT_ID }}/$IMAGE_NAME:latest

      - name: Deploy to CloudRUn
        run: gcloud run deploy ${{ secrets.PROJECT_ID }} --image gcr.io/${{ secrets.PROJECT_ID }}/$IMAGE_NAME:latest --platform managed --region $REGION
