name: Publish to GCR 
on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Login to GCR
        env:
          PROJECT_ID: horizontal-veld-327901
        uses: google-github-actions/setup-gcloud@v0.3.0 
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
          
      - name: Build Docker Image
        env:
          IMAGE_NAME: linux_tweet_app_el
          PROJECT_ID: horizontal-veld-327901
          VERSION: 0.1.0
        run: docker build -t $IMAGE_NAME:$VERSION . 
        
      - name: Configure Docker Client
        run:  |-
          gcloud auth configure-docker --quiet 
        
      - name: Push Docker Image to Container Registry GCR
        env: 
          IMAGE_NAME: linux_tweet_app_el
          PROJECT_ID: horizontal-veld-327901
          VERSION: 0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$VERSION 
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$VERSION 
